format_version: v1.0
type: UniqueComponent
attributes: {id: svcBLE_DIS}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DIS_FW_REV_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: DIS_FW_REV_STRING}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 0.9.0.4}
  - type: String
    attributes: {id: DIS_MANU_NAME_STRING}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: MCHP}
  - type: String
    attributes: {id: DIS_MODEL_NUM_STRING}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Coming Soon}
- type: ElementPosition
  attributes: {x: '268', y: '344', id: svcBLE_DIS}
