format_version: v1.0
type: UniqueComponent
attributes: {id: libBLEStack}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: APP_TRP_SERVER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: 'true'}
  - type: Boolean
    attributes: {id: BLE_SYS_SLEEP_MODE_EN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CUSTOM_ANT_GAIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: '3'}
  - type: String
    attributes: {id: CUSTOM_ANT_REGION}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: ETSI}
  - type: String
    attributes: {id: GAP_ADV_DATA}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: '0x02, 0x01, 0x04, 0x05, 0x16, 0xDA,
            0xFE, 0xFF, 0x03'}
  - type: Integer
    attributes: {id: GAP_ADV_DATA_LEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: '9'}
  - type: Boolean
    attributes: {id: GAP_ADV_DATA_LOCAL_NAME_EN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: bz_prov, value: 'false'}
  - type: Hex
    attributes: {id: GAP_ADV_DATA_SERVICE_DATA}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: bz_prov, value: '65283'}
  - type: Boolean
    attributes: {id: GAP_ADV_DATA_SERVICE_DATA_EN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: bz_prov, value: 'true'}
  - type: Hex
    attributes: {id: GAP_ADV_DATA_SERVICE_UUID}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: bz_prov, value: '65242'}
  - type: Comment
    attributes: {id: GAP_ADV_DATA_VALUE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '0x02, 0x01, 0x04, 0x05, 0x16, 0xDA, 0xFE, 0xFF, 0x03'}
  - type: String
    attributes: {id: GAP_EXT_ADV_DATA}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: '0x02, 0x01, 0x04, 0x0B, 0x09, 0x70,
            0x69, 0x63, 0x33, 0x32, 0x63, 0x78, 0x2D, 0x62, 0x7A'}
  - type: String
    attributes: {id: GAP_EXT_ADV_DATA_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: '0x02, 0x01, 0x04, 0x0B, 0x09, 0x70,
            0x69, 0x63, 0x33, 0x32, 0x63, 0x78, 0x2D, 0x62, 0x7A'}
  - type: Integer
    attributes: {id: GAP_EXT_ADV_DATA_LEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: '15'}
  - type: Integer
    attributes: {id: GAP_EXT_ADV_DATA_LEN_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: '15'}
  - type: String
    attributes: {id: GAP_EXT_SCAN_RSP_DATA}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: '0x0B, 0x09, 0x70, 0x69, 0x63, 0x33,
            0x32, 0x63, 0x78, 0x2D, 0x62, 0x7A'}
  - type: String
    attributes: {id: GAP_EXT_SCAN_RSP_DATA_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: '0x0B, 0x09, 0x70, 0x69, 0x63, 0x33,
            0x32, 0x63, 0x78, 0x2D, 0x62, 0x7A'}
  - type: Integer
    attributes: {id: GAP_EXT_SCAN_RSP_DATA_LEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: '12'}
  - type: Integer
    attributes: {id: GAP_EXT_SCAN_RSP_DATA_LEN_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: '12'}
  - type: String
    attributes: {id: GAP_SCAN_RSP_DATA}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: '0x14, 0x09, 0x42, 0x5A, 0x5F, 0x50,
            0x72, 0x6F, 0x76, 0x5F, 0x4D, 0x75, 0x6C, 0x74, 0x69, 0x53, 0x65, 0x6E,
            0x73, 0x6F, 0x72'}
  - type: Integer
    attributes: {id: GAP_SCAN_RSP_DATA_LEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: '21'}
  - type: String
    attributes: {id: GAP_SCAN_RSP_DATA_LOCAL_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: BZ_Prov_MultiSensor}
  - type: Comment
    attributes: {id: GAP_SCAN_RSP_DATA_VALUE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '0x14, 0x09, 0x42, 0x5A, 0x5F, 0x50, 0x72, 0x6F, 0x76,
            0x5F, 0x4D, 0x75, 0x6C, 0x74, 0x69, 0x53, 0x65, 0x6E, 0x73, 0x6F, 0x72'}
  - type: Boolean
    attributes: {id: USE_CUSTOM_ANT_GAIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: libBLEStack, value: 'false'}
- type: ElementPosition
  attributes: {x: '370', y: '60', id: libBLEStack}
