format_version: v1.0
type: UniqueComponent
attributes: {id: trng}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TRNG_STANDBY}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: trngEnableEvent}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: trngEnableInterrupt}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '460', y: '20', id: trng}
