format_version: v1.0
type: UniqueComponent
attributes: {id: bz_prov}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: ZIGBEE_DEV_TYPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: bz_prov, value: ZIGBEE_MULTI_SENSOR}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: BLE_ZIGBEE_PROV_Dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: ZIGBEE_MULTI_SENSOR}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: BLE_ZIGBEE_PROV_Capability}
- type: ElementPosition
  attributes: {x: '253', y: '227', id: bz_prov}
